export enum ErrorCode {
  /**
   * 클라이언트 에러 (400-499)
   */
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT = "CONFLICT",
  RESOURCE_EXISTS = "RESOURCE_EXISTS",

  /**
   * 서버 에러 (500-599)
   */
  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",

  /**
   * Server 관련 에러
   */
  //  조회 관련
  SERVER_DATA_UNREGISTERED = "SERVER_DATA_UNREGISTERED",
  SERVER_DATA_SEARCH_ERROR = "SERVER_DATA_SEARCH_ERROR",
  SERVER_DATA_NOT_FOUND = "SERVER_DATA_NOT_FOUND",
  /**
   * ZDM 관련 에러
   */
  ZDM_DATA_SEARCH_ERROR = "ZDM_DATA_SEARCH_ERROR",
  ZDM_DATA_NOT_FOUND = "ZDM_DATA_NOT_FOUND",
  /**
   *  Backup 작업 관련 에러
   */
  //  조회 관련
  BACKUP_DATA_SEARCH_ERROR = "BACKUP_DATA_SEARCH_ERROR",
  BACKUP_DATA_MAPPING_ERROR = "BACKUP_DATA_MAPPING_ERROR",
  //  등록 관련
  //  삭제 관련
  //  수정 관련
  //  모니터링 관련
}