
export enum ErrorCode {
  /**
   * 클라이언트 에러 (400-499)
   */
  CONFLICT = "CONFLICT",
  RESOURCE_EXISTS = "RESOURCE_EXISTS",

  /**
   * 서버 에러 (500-599)
   */
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  // 일반 에러
  INTERNAL_ERROR = "INTERNAL_ERROR",

  // 인증/인가 관련 에러
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // 요청 관련 에러
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",

  // 비즈니스 로직 관련 에러
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  DATA_PROCESSING_ERROR = "DATA_PROCESSING_ERROR",

  // 데이터베이스 관련 에러
  DATABASE_ERROR = "DATABASE_ERROR",
  CONNECTION_ERROR = "CONNECTION_ERROR",
  QUERY_ERROR = "QUERY_ERROR",
  DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR",
  DATA_MAPPING_ERROR = "DATA_MAPPING_ERROR",
  TRANSACTION_ERROR = "TRANSACTION_ERROR",

  // 외부 의존성 관련 에러
  DEPENDENCY_ERROR = "DEPENDENCY_ERROR",

  // 기타
  UNKNOWN_ERROR = "UNKNOWN_ERROR"
}